[package]
name = "chit-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web-actors = "4.2.0"
actix-web = "4.3.1"
actix = "0.13.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["fmt"] }
